name: Test

on:
    push:
        branches: ["**"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run tests
              run: docker-compose -f docker-compose.yml -f docker-compose-test.yml run off-product-environmental-impact pytest tests
